# ----------------------------------------------------------------------------------
# App.toml
# NOTE: Can be committed. Do not add secrets to this file. Use .env for this purpose.
# ----------------------------------------------------------------------------------

name = "apiker-demo"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
main = "./dist/shim.mjs"
# To use your own route, set workers_dev to false and fill out the following
#route = "your.domain.com/*"

[build]
command = "npm install && npm run build"